# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainscreen.ui'
#
# Created: Wed May 15 00:23:40 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(991, 690)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8("background:#d5d1a2\n"
"\n"
""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(730, 30, 221, 61))
        self.pushButton_6.setStyleSheet(_fromUtf8("font-size:30px;"))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(860, 630, 121, 31))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(240, 40, 441, 541))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setStyleSheet(_fromUtf8("padding:10px;"))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.widget)
        self.pushButton_2.setStyleSheet(_fromUtf8("padding:10px;"))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.widget)
        self.pushButton_3.setStyleSheet(_fromUtf8("padding:10px;"))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.widget)
        self.pushButton_4.setStyleSheet(_fromUtf8("padding:10px;"))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.widget)
        self.pushButton_5.setStyleSheet(_fromUtf8("padding:10px;"))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 0, 201, 611))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.frame_2 = QtGui.QFrame(self.widget1)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.widget2 = QtGui.QWidget(self.frame_2)
        self.widget2.setGeometry(QtCore.QRect(10, 10, 181, 101))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.tarih = QtGui.QVBoxLayout(self.widget2)
        self.tarih.setMargin(0)
        self.tarih.setObjectName(_fromUtf8("tarih"))
        self.label = QtGui.QLabel(self.widget2)
        self.label.setStyleSheet(_fromUtf8("font-size:40px;"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.tarih.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.widget2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tarih.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.widget2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.tarih.addWidget(self.label_3)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame = QtGui.QFrame(self.widget1)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.widget3 = QtGui.QWidget(self.frame)
        self.widget3.setGeometry(QtCore.QRect(10, 10, 181, 111))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_5 = QtGui.QLabel(self.widget3)
        self.label_5.setStyleSheet(_fromUtf8("font-size:25px;font-weight:bold;"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.widget3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_3 = QtGui.QFrame(self.widget1)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.widget4 = QtGui.QWidget(self.frame_3)
        self.widget4.setGeometry(QtCore.QRect(10, 10, 181, 121))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget4)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_7 = QtGui.QLabel(self.widget4)
        self.label_7.setStyleSheet(_fromUtf8("font-size:25px;font-weight:bold;"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.widget4)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.widget4)
        self.label_9.setStyleSheet(_fromUtf8("font-style:italic;"))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.widget4)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_2.addWidget(self.label_10)
        self.verticalLayout_4.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Ana Ekran", None))
        self.pushButton_6.setText(_translate("MainWindow", "Hayde !", None))
        self.pushButton_7.setText(_translate("MainWindow", "Topuk !", None))
        self.pushButton.setText(_translate("MainWindow", "Puan Durumu", None))
        self.pushButton_2.setText(_translate("MainWindow", "Fikstür", None))
        self.pushButton_3.setText(_translate("MainWindow", "Takım", None))
        self.pushButton_4.setText(_translate("MainWindow", "Transfer", None))
        self.pushButton_5.setText(_translate("MainWindow", "İdman", None))
        self.label_4.setText(_translate("MainWindow", "Edirne Güreş Kulübü", None))
        self.label.setText(_translate("MainWindow", "15", None))
        self.label_2.setText(_translate("MainWindow", "Haziran", None))
        self.label_3.setText(_translate("MainWindow", "2013", None))
        self.label_5.setText(_translate("MainWindow", "Bütçe", None))
        self.label_6.setText(_translate("MainWindow", "90 000 TL", None))
        self.label_7.setText(_translate("MainWindow", "Sonraki Maç", None))
        self.label_8.setText(_translate("MainWindow", "Koca Yusuf", None))
        self.label_9.setText(_translate("MainWindow", "ile", None))
        self.label_10.setText(_translate("MainWindow", "Kurtereli", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

